version: '2.2'

services:

  geoserver:
    image: geonode/geoserver:2.15.x
    depends_on:
      - postgis
    ports:
      - "8081:8080"
    volumes:
      - geoserver_data_dir:/geoserver_data/data

  postgis:
    image: geonode/postgis
    ports:
      - "25432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups

volumes:
  geoserver_data_dir:
    name: smartt-gsdatadir
  dbdata:
    name: smartt-dbdata
  dbbackups:
    name: smartt-dbbackups
